package com.hedylogos.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MESSAGE.
 */
public class Message {

    private String id;
    private String conversationId;
    private String content;
    private String from;
    private String timestamp;
    private String messageId;
    private String type;

    public Message() {
    }

    public Message(String id) {
        this.id = id;
    }

    public Message(String id, String conversationId, String content, String from, String timestamp, String messageId, String type) {
        this.id = id;
        this.conversationId = conversationId;
        this.content = content;
        this.from = from;
        this.timestamp = timestamp;
        this.messageId = messageId;
        this.type = type;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getConversationId() {
        return conversationId;
    }

    public void setConversationId(String conversationId) {
        this.conversationId = conversationId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getFrom() {
        return from;
    }

    public void setFrom(String from) {
        this.from = from;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    public String getMessageId() {
        return messageId;
    }

    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

}
