package com.hedylogos.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.hedylogos.Utils.TimeUtils;

/**
 * Entity mapped to table MESSAGE.
 */
public class Message {
    /**
    LocalId	INTEGER	yes	yes
    ServerId	INTEGER
    Status	INTEGER
    Type	INTEGER
    Message	TEXT
    CreateTime	INTEGER
    SendType	INTEGER
    Metadata	TEXT
    SenderId	INTEGER
     **/
    private Long msgId;
    private Long sender;
    private Long receiver;
    private String contents;
    private Long timestamp;
    private String conversation;
    private Integer type;

    public Message() {
    }
    public Message(Long msgId, Long sender, Long receiver,String contents) {
        this(msgId,1010l,receiver,contents, TimeUtils.getTimestamp(), "5530b32eafd197814b46a497", -1);
    }
    public Message(Long msgId, Long sender, Long receiver, String contents, Long timestamp, String conversation, Integer type) {
        this.msgId = msgId;
        this.sender = sender;
        this.receiver = receiver;
        this.contents = contents;
        this.timestamp = timestamp;
        this.conversation = conversation;
        this.type = type;
    }

    public Long getMsgId() {
        return msgId;
    }

    public void setMsgId(Long msgId) {
        this.msgId = msgId;
    }

    public Long getSender() {
        return sender;
    }

    public void setSender(Long sender) {
        this.sender = sender;
    }

    public Long getReceiver() {
        return receiver;
    }

    public void setReceiver(Long receiver) {
        this.receiver = receiver;
    }

    public String getContents() {
        return contents;
    }

    public void setContents(String contents) {
        this.contents = contents;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    public String getConversation() {
        return conversation;
    }

    public void setConversation(String conversation) {
        this.conversation = conversation;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

}

